version: '3'

services:
  react-app:
    build:
      context: .
      dockerfile: 'Dockerfile.dev'
    ports:
      - '3000:3000'
    volumes:
      - /var/node/node_modules
      - .:/var/node
  tests:
    build:
      context: .
      dockerfile: 'Dockerfile.dev'
    volumes:
      - /var/node/node_modules
      - .:/var/node
    command: ['npm', 'run', 'test']
